apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: backstage-lambda-template
  title: Create Lambda
  description: Provision and configure a new AWS Lambda function.
  tags:
    - 'single-resource'
    - 'product-serverless'
    - 'product-containers'
    - 'tier-techlead'
spec:
  owner: example-org/platform-team
  type: AWS Service
  parameters:
    - title: Name
      required:
        - lambda_name
        - deployment_env
        - github_org
        - github_repo
      properties:
        lambda_name:
          title: Lambda Name
          type: string
          description: A unique name for your Lambda Function
        deployment_env:
          title: Environment
          type: string
          description: The environment the service will be deployed in
          default: dev
          enum:
            - dev
            - test
            - staging
            - prod
          enumNames:
            - 'dev'
            - 'test'
            - 'staging'
            - 'prod'
        github_org:
          title: GitHub Organization
          type: string
          description: The organization in GitHub that should own the deployment
          ui:field: GitOrgPicker
        github_repo:
          title: GitHub Repository Name
          type: string
          description: Enter the name of the organization's GitHub repository used for IaC configuration (defaulted to iac)
          default: "iac"
    - title: Lambda Parameters
      required:
        - handler
        - local_existing_package
        - lambda_role
        - runtime
      properties:
        handler:
          title: Handler
          type: string
          description: Lambda Function entrypoint in your code
        local_existing_package:
          title: Local Existing Package
          type: string
          description: The absolute path to an existing zip-file to use
        lambda_role:
          title: Lambda Role
          type: string
          description: IAM role ARN attached to the Lambda Function
        runtime:
          title: Runtime
          type: string
          description: Lambda Function runtime
    - title: Optional Lambda Parameters
      properties:
        lambda_description:
          title: Description
          type: string
          description: Description of your Lambda Function (or Layer)
        hash_extra:
          title: Hash Extra
          type: string
          description: The string to add into hashing function. Useful when building same source path for different functions
        #environment_variables
        #kms_key_arn
        package_type:
          title: Package Type
          type: string
          description: "The Lambda deployment package type. Valid options: Zip or Image"
        #publish
        #s3_object_tags
        source_path:
          title: Source Path
          type: string
          description: The absolute path to a local file or directory containing your Lambda source code
        timeout:
          title: Timeout
          type: number
          description: The amount of time your Lambda Function has to run in seconds
        #vpc_security_group_ids
        #vpc_subnet_ids
  steps:
    - id: backstage_request_with_input
      name: backstage request with inputs
      action: http:backstage:request
      input:
        method: 'POST'
        path: 'proxy/awsExecuteEndpoint/execute_platform'
        headers:
          content-type: 'application/json'
        body:
            workflow_name: ${{ "NewIAC" }}
            workflow_id: ${{ "NewIAC-lambda-" + parameters.github_org + "-" + parameters.lambda_name + "-" + parameters.deployment_env }}
            task_queue: ${{ platform.taskQueue }}
            workflow_args:
              branch_name: ${{ parameters.github_org + "/" + parameters.deployment_env + "/lambda/" + parameters.lambda_name }}
              repo_owner: ${{ parameters.github_org }}
              repo_name: ${{ parameters.github_repo }}
              pr_title: '${{ "Add Lambda: " + parameters.lambda_name + " (" + parameters.github_org + "/" + parameters.deployment_env + ")" }}'
              pr_body: '${{ "Provisions a Lambda function named " + parameters.lambda_name + " in the " + parameters.deployment_env + " environment for " + parameters.github_org + "." }}'
              module_source_base: ${{ "git@github.example.com:example-org/Example-IaC-Modules.git/" }}
              env_config_path: ${{ "env/{environment}/env.hcl" }}
              resource_type: ${{ "lambda" }}
              resource_config:
                name: ${{ parameters.lambda_name }}
                environments: ${{ parameters.deployment_env }}
                config:
                  function_name: ${{ parameters.lambda_name }}
                  name: ${{ parameters.lambda_name }}
                  description: ${{ parameters.lambda_description }}
                  handler: ${{ parameters.handler }}
                  hash_extra: ${{ parameters.hash_extra }}
                  lambda_role: ${{ parameters.lambda_role }}
                  local_existing_package: ${{ parameters.local_existing_package }}
                  package_type: ${{ parameters.package_type }}
                  runtime: ${{ parameters.runtime }}
                  source_path: ${{ parameters.source_path }}
                  timeout: ${{ parameters.timeout }}
  output:
    links:
      - title: 'Go to pull request'
        url: ${{"https://github.example.com/"+parameters.github_org+"/"+parameters.github_repo+"/pulls"}}
        icon: github
